apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-fuse-csi-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: dummy-storage-class  # we can use any dummy name here
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io # this is the most important value
    volumeHandle: gke-object-storage-101-boris # here you enter the bucket name
    volumeAttributes:
      gcsfuseLoggingSeverity: warning