apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-fuse-csi-static-pvc
  namespace: mydemo1ns
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: gcs-fuse-csi-pv  # this is name of the pv created earlier
  storageClassName: dummy-storage-class # this is the name of storage class mentioned in the pv