# instead of creating a custom storage class, we can also directly use the GKE storage classes available in the cluster
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: gke-pd-standard-rwo-sc
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer # the sc will wait for a pod to be created before binding to the pvc
allowVolumeExpansion: true # this mean that the pd can be increased
reclaimPolicy: Retain # the pd will be available after the pvc is deleted; another option is "delete"
parameters:
  type: pd-balanced # Other Options supported are pd-ssd, pd-standard

# STORAGE CLASS 
# 1. A StorageClass provides a way for administrators 
# to describe the "classes" of storage they offer.
# 2. Here we are offering GCP PD Storage for GKE Cluster