apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate 
  template: 
    metadata: 
      labels: 
        app: mysql
    spec: 
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD # when using MySQL in Kubernetes, you need to pass in the root_password as env
              value: dbpassword11 
          ports:
            - containerPort: 3306 # this is the port for MySQL
              name: mysql    
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql    
            - name: usermanagement-dbcreation-script
              mountPath: /docker-entrypoint-initdb.d #https://hub.docker.com/_/mysql Refer Initializing a fresh instance                                            
      volumes: 
        - name: mysql-persistent-storage
          persistentVolumeClaim:  # this PVC will automatically provision persistent disks
            claimName: mysql-pv-claim
        - name: usermanagement-dbcreation-script
          configMap:   # we are mounting the configMap as a volume
            name: usermanagement-dbcreation-script

